### ISSUE TITLE
Confirm to RFC RFC0043: Reproducible builds

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/poetry-install#19]
To confirm to RFC0043 this buildpack should ensure that builds are reproducible. Specifically it should not include a `built_at` metadata field. In the tests that leverage this field to assert layer reuse, we should instead compare layer SHA values across rebuilds.

See also the tracking issue: https://github.com/paketo-buildpacks/rfcs/issues/165.

**Comment by ForestEckhardt** [comment]
@robdimsdale As far as I can tell this buildpack does not actually reuse a layer currently. It has a cache layer that is revived each build but the build happens regardless of the metadata found in the previous build. I think that means a layer reuse test is not necessary. If I am missing something feel free to point it out.
